/**
 * Single source of truth for all UI copy in the Embr web app.
 *
 * Usage: import { copy } from '@/lib/copy';
 *
 * Sections:
 *   brand, nav, onboarding, dashboard, jobs, applications, resumes,
 *   voice, personas, profile, settings, learn, transparency, upgrade,
 *   errors, success, confirmations, actions, emptyStates, pricing, ethics,
 *   eduPromo, marketing, trust
 */

export const copy = {
  brand: {
    name: 'Embr',
    tagline: 'A creator-focused social platform for your community.',
    homeTitle: 'Welcome to Embr',
    homeDescription: 'A creator-focused social platform for your community.',
    ariaLabel: 'Embr home',
    pageTitle: (section: string) => `${section} — Embr`,
  },

  nav: {
    feed: 'Feed',
    discover: 'Discover',
    create: 'Create',
    groups: 'Groups',
    events: 'Events',
    mutualAid: 'Mutual Aid',
    marketplace: 'Marketplace',
    music: 'Music',
    gigs: 'Gigs',
    earnings: 'Earnings',
    messages: 'Messages',
    profile: 'Profile',
    notifications: 'Notifications',
    settings: 'Settings',
    signOut: 'Sign out',
    toggleMenu: 'Toggle menu',
    primaryNav: 'Primary navigation',
    userMenu: 'User menu',
    quickCreate: {
      hostEvent: 'Host Event',
      createGroup: 'Create Group',
      sell: 'Sell',
    },
  },

  onboarding: {
    signIn: 'Sign in',
    signingIn: 'Signing in...',
    signInSubtitle: 'Continue building with Embr.',
    signInTitle: 'Sign in',
    createAccount: 'Create account',
    creatingAccount: 'Creating account...',
    createAccountTitle: 'Create account',
    createAccountSubtitle: 'Build your creator space on Embr.',
    forgotPassword: 'Forgot password?',
    needAccount: 'Need an account?',
    alreadyHaveAccount: 'Already have an account?',
    resetPassword: 'Reset password',
    resetPasswordSubtitle: 'Enter your email and we will send a secure reset link.',
    sendResetLink: 'Send reset link',
    sending: 'Sending...',
    checkEmail: 'Check your email',
    checkEmailDescription: (email: string) =>
      `If an account exists for ${email}, a reset link has been sent.`,
    signInToContinue: 'Sign in to continue',
    signInToContinueDesc: 'Create an account or sign in to access Embr.',
    welcomeBack: 'Welcome back',
    welcomeBackDesc: 'Continue to your feed.',
    goToFeed: 'Go to feed',
    loading: 'Loading',
    loadingDesc: 'Checking your authentication state.',
    redirecting: 'Redirecting you to sign in',
    redirectingDesc: 'Please wait while we verify your session.',
  },

  dashboard: {
    feed: {
      title: 'Feed',
      subtitle: "Stay up to date with what's new from creators.",
    },
    discover: {
      title: 'Discover',
      subtitle: 'Find amazing creators and connect with the community',
    },
    messages: {
      title: 'Messages',
      subtitle: 'Connect and chat with other creators.',
    },
    notifications: {
      title: 'Notifications',
      unread: (count: number) =>
        `${count} unread notification${count === 1 ? '' : 's'}`,
      allCaughtUp: 'You are all caught up.',
      markAllRead: 'Mark all read',
      deleteRead: 'Delete read',
      loadMore: 'Load more',
    },
    earnings: {
      title: 'Earnings',
      subtitle:
        'See where your money comes from. Transparent breakdown, zero hidden fees.',
      summary: 'Summary',
      transactions: 'Transactions',
      requestPayout: 'Request Payout',
    },
    create: {
      title: 'Create',
      subtitle: 'Share something with your community.',
    },
    groups: {
      title: 'Groups',
      subtitle: 'Organize and connect with focused communities.',
    },
    events: {
      title: 'Events',
      subtitle: 'Find and host events in your community.',
      upcoming: 'Upcoming',
      past: 'Past',
      allTypes: 'All Types',
    },
    marketplace: {
      title: 'Marketplace',
      subtitle: 'Buy, sell, and trade with your community. 2% platform fee — nothing hidden.',
    },
    mutualAid: {
      title: 'Mutual Aid',
      subtitle: 'Give and receive support within your community.',
    },
    music: {
      title: 'Music',
      subtitle: 'Discover, share, and license music from independent artists.',
    },
    safety: {
      title: 'Safety',
      subtitle: 'Keep Embr a safe and welcoming space.',
    },
  },

  jobs: {
    findWork: {
      title: 'Find Work',
      subtitle: 'Browse opportunities to earn. Filter by what matters to you.',
    },
    myGigs: 'My Gigs',
    postGig: '+ Post a Gig',
    manageGigs: 'Manage gigs',
    gigDetail: 'Gig details',
    bookGig: 'Book this gig',
  },

  applications: {
    apply: 'Apply',
    applyNow: 'Apply now',
    applied: 'Applied',
    application: 'Application',
    applications: 'Applications',
    viewApplications: 'View applications',
    applicationSubmitted: 'Application submitted',
    withdrawApplication: 'Withdraw application',
  },

  resumes: {
    resume: 'Resume',
    uploadResume: 'Upload resume',
    viewResume: 'View resume',
    noResume: 'No resume uploaded yet.',
    resumeOptional: 'Resume (optional)',
  },

  voice: {
    persona: 'Persona',
    voiceProfile: 'Voice profile',
    tone: 'Tone',
    style: 'Style',
    voiceSettings: 'Voice settings',
    configureVoice: 'Configure your voice persona',
  },

  personas: {
    creator: 'Creator',
    user: 'User',
    admin: 'Admin',
    creatorMode: 'Creator mode',
    creatorModeDesc: 'Unlocks gig posting, music upload, and creator tools',
    switchToCreator: 'Switch to creator mode',
  },

  profile: {
    loading: 'Loading profile',
    loadingDesc: 'Please wait while we load your profile.',
    followers: 'Followers',
    following: 'Following',
    posts: 'Posts',
    editProfile: 'Edit profile',
    changePhoto: 'Change profile photo',
    bio: 'Bio',
    location: 'Location',
    website: 'Website',
    save: 'Save',
    saving: 'Saving...',
    follow: 'Follow',
    unfollow: 'Unfollow',
    message: 'Message',
    tip: 'Tip',
    noPostsYet: 'No posts yet.',
    failedToLoadPosts: 'Failed to load posts',
  },

  settings: {
    title: 'Settings',
    account: 'Account',
    privacyMonetization: 'Privacy & Monetization',
    notifications: 'Notifications',
    dangerZone: 'Danger Zone',
    privateAccount: 'Private account',
    privateAccountDesc: 'Only approved followers can see your posts',
    allowTips: 'Allow tips',
    allowTipsDesc: 'Let others send you tips on your posts',
    emailNotifications: 'Email notifications',
    emailNotificationsDesc: 'Receive activity updates via email',
    pushNotifications: 'Push notifications',
    pushNotificationsDesc: 'In-app alerts for messages and activity',
    notificationLevel: {
      all: { label: 'All activity', desc: 'Likes, comments, follows, messages' },
      mentions: {
        label: 'Mentions only',
        desc: 'Only when someone tags or replies to you',
      },
      none: { label: 'None', desc: 'Turn off all notifications' },
    },
    deleteAccount: 'Delete account',
    deleteAccountDesc: 'Permanently delete your account and all data',
    deleteConfirm: 'Are you sure? This cannot be undone.',
    deleting: 'Deleting…',
    deletePermanently: 'Delete permanently',
    saved: 'Saved',
    couldNotSave: 'Could not save',
    couldNotSaveDesc: 'Please try again.',
    uploadFailed: 'Upload failed',
    uploadFailedDesc: 'Please try a smaller image.',
    deletionFailed: 'Deletion failed',
    deletionFailedDesc: 'Contact support if this continues.',
  },

  learn: {
    learnMore: 'Learn more',
    documentation: 'Documentation',
    guide: 'Guide',
    tutorial: 'Tutorial',
    howItWorks: 'How it works',
    resources: 'Resources',
    faq: 'FAQ',
  },

  transparency: {
    platformFee: '2% platform fee — nothing hidden.',
    creatorRevenue: '85–90% goes to you',
    openSource: 'Open source',
    noHiddenFees: 'No hidden fees',
    earningsBreakdown: 'Full earnings breakdown',
    feeStructure: 'Fee structure',
  },

  upgrade: {
    upgrade: 'Upgrade',
    upgradeNow: 'Upgrade now',
    unlockFeatures: 'Unlock features',
    viewPlans: 'View plans',
    currentPlan: 'Current plan',
    freePlan: 'Free plan',
  },

  errors: {
    generic: 'Something went wrong. Please try again.',
    networkError:
      'Unable to connect. Please check your connection and try again.',
    invalidCredentials: 'Invalid credentials.',
    signupFailed: 'Signup failed.',
    failedToLoad: 'Failed to load.',
    failedToSave: 'Could not save',
    failedToSaveDesc: 'Please try again.',
    uploadFailed: 'Upload failed',
    uploadFailedDesc: 'Please try a smaller image.',
    deletionFailed: 'Deletion failed',
    deletionFailedDesc: 'Contact support if this continues.',
    resetEmailFailed: 'Failed to send reset email.',
    failedToLoadPosts: 'Failed to load posts',
    validationFailed: 'Please check the form and try again.',
    passwordTooShort: 'Password must be at least 8 characters.',
    passwordMismatch: 'Passwords do not match.',
    usernameTooShort: 'Username must be at least 3 characters.',
    unauthorized: 'You are not authorized to do that.',
    notFound: 'Not found.',
  },

  success: {
    saved: 'Saved',
    profilePhotoUpdated: 'Profile photo updated',
    sent: 'Sent',
    submitted: 'Submitted',
    created: 'Created',
    updated: 'Updated',
    deleted: 'Deleted',
    resetEmailSent: 'Reset email sent',
    passwordChanged: 'Password changed',
    settingsSaved: 'Settings saved',
  },

  confirmations: {
    deleteAccount:
      'Are you sure you want to delete your account? This cannot be undone.',
    deletePost: 'Are you sure you want to delete this post?',
    confirmDelete: 'Confirm deletion',
    cancel: 'Cancel',
    confirm: 'Confirm',
    yes: 'Yes',
    no: 'No',
  },

  actions: {
    save: 'Save',
    saving: 'Saving...',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    submit: 'Submit',
    send: 'Send',
    loading: 'Loading',
    loadMore: 'Load more',
    viewAll: 'View all',
    close: 'Close',
    back: 'Back',
    next: 'Next',
    done: 'Done',
    markAllRead: 'Mark all read',
    deleteAllRead: 'Delete read',
    refresh: 'Refresh',
    share: 'Share',
    report: 'Report',
    block: 'Block',
    mute: 'Mute',
    like: 'Like',
    comment: 'Comment',
    reply: 'Reply',
    follow: 'Follow',
    unfollow: 'Unfollow',
    search: 'Search',
    filter: 'Filter',
    apply: 'Apply filters',
    clear: 'Clear filters',
    upload: 'Upload',
    download: 'Download',
    preview: 'Preview',
    post: 'Post',
  },

  emptyStates: {
    noJobs: 'No gigs available right now.',
    noJobsDesc: 'Check back soon or post your own gig.',
    noPosts: 'No posts yet.',
    noPostsDesc: 'Be the first to post something.',
    noNotifications: 'You are all caught up.',
    noMessages: 'No messages yet.',
    noMessagesDesc: 'Start a conversation with a creator.',
    noEvents: 'No events found.',
    noEventsDesc: 'Try adjusting your filters or check back later.',
    noListings: 'No listings available.',
    noListingsDesc: 'Try adjusting your search or filters.',
    noResults: 'No results found.',
    noResultsDesc: 'Try adjusting your search or filters.',
    noFollowers: 'No followers yet.',
    noFollowing: 'Not following anyone yet.',
    noTransactions: 'No transactions yet.',
    noEarnings: 'No earnings yet.',
    noEarningsDesc: 'Start creating and earning today.',
    noGroups: 'No groups yet.',
    noGroupsDesc: 'Join or create a group to get started.',
  },

  pricing: {
    free: 'Free',
    pro: 'Pro',
    perMonth: '/month',
    getStarted: 'Get started',
    platformFee: '2%',
    noHiddenFees: 'No hidden fees',
    creatorKeeps: '85–90% creator revenue share',
    viewPricing: 'View pricing',
  },

  ethics: {
    creatorFirst: 'Creator-first',
    transparentFees: 'Transparent fees',
    communityOwned: 'Community owned',
    openSource: 'Open source',
    privacyFirst: 'Privacy first',
    noAds: 'No ads',
    noAlgorithmicManipulation: 'No algorithmic manipulation',
    dataPortability: 'Your data, your terms',
    moderation: 'Community-led moderation',
  },

  // Keys migrated from i18n.config.ts (eduPromo, marketing, trust)
  eduPromo: {
    title: 'Learn and grow',
    subtitle: 'Access tutorials, guides, and community resources.',
    cta: 'Explore resources',
    badge: 'Education',
    featuredGuide: 'Getting started guide',
    communityTips: 'Community tips',
    creatorPlaybook: 'Creator playbook',
  },

  marketing: {
    heroTitle: 'Build your creator space',
    heroSubtitle: 'A platform built by creators, for creators.',
    ctaPrimary: 'Get started free',
    ctaSecondary: 'Learn more',
    featureTitle: 'Everything you need to create',
    testimonialLabel: 'What creators say',
    socialProof: 'Trusted by creators',
    valueProps: {
      ownership: 'Own your audience',
      revenue: 'Keep 85–90% of revenue',
      tools: 'Professional creator tools',
      community: 'Built-in community features',
    },
  },

  trust: {
    securePayments: 'Secure payments',
    verifiedCreators: 'Verified creators',
    communityModerated: 'Community moderated',
    dataPrivacy: 'Your data stays yours',
    supportAvailable: 'Support available',
    encryptedData: 'End-to-end encrypted messages',
    gdprCompliant: 'GDPR compliant',
    noDataSelling: 'We never sell your data',
  },
} as const;

export type Copy = typeof copy;
